// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package gosql_queries

import (
	"context"
)

const addLesson = `-- name: AddLesson :exec
INSERT INTO lessons (topic, started_date, repetitions_dates, amount_of_cards)
VALUES (?, ?, json (?), ?)
`

type AddLessonParams struct {
	Topic         string
	StartedDate   string
	Json          interface{}
	AmountOfCards int64
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) error {
	_, err := q.db.ExecContext(ctx, addLesson,
		arg.Topic,
		arg.StartedDate,
		arg.Json,
		arg.AmountOfCards,
	)
	return err
}

const getAllLessons = `-- name: GetAllLessons :many
SELECT id, topic, started_date, repetitions_dates, amount_of_cards, created_at, updated_at FROM lessons
`

func (q *Queries) GetAllLessons(ctx context.Context) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getAllLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.StartedDate,
			&i.RepetitionsDates,
			&i.AmountOfCards,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
