// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package gosql_queries

import (
	"context"
)

const addLesson = `-- name: AddLesson :exec
INSERT INTO lessons (topic, amount_of_cards)
VALUES (?, ?)
`

type AddLessonParams struct {
	Topic         string
	AmountOfCards int64
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) error {
	_, err := q.db.ExecContext(ctx, addLesson, arg.Topic, arg.AmountOfCards)
	return err
}
