// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gosql_queries

import (
	"database/sql"
)

type Lesson struct {
	ID            string
	Topic         string
	StartedDate   sql.NullString
	AmountOfCards int64
	CreatedAt     string
	UpdatedAt     string
}
