// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gosql_queries

import (
	"database/sql"
)

type Lesson struct {
	ID               int64
	Topic            string
	StartedDate      string
	RepetitionsDates string
	AmountOfCards    int64
	CreatedAt        string
	UpdatedAt        string
}

type User struct {
	ID          int64
	UserID      sql.NullInt64
	AccessToken sql.NullString
	ApiKey      sql.NullString
	Showed      int64
}
