// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gosql_queries

type Lesson struct {
	ID               int64
	Topic            string
	StartedDate      string
	RepetitionsDates string
	AmountOfCards    int64
	CreatedAt        string
	UpdatedAt        string
}
