// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package gosql_queries

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (
    access_token,
    showed
) VALUES (?, ?)
`

type AddUserParams struct {
	AccessToken sql.NullString
	Showed      int64
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.AccessToken, arg.Showed)
	return err
}

const addUserID = `-- name: AddUserID :exec
UPDATE users
SET user_id = ?
WHERE id = 1
`

func (q *Queries) AddUserID(ctx context.Context, userID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, addUserID, userID)
	return err
}

const getAPIKEY = `-- name: GetAPIKEY :one
SELECT api_key FROM users
WHERE id = 1
`

func (q *Queries) GetAPIKEY(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAPIKEY)
	var api_key sql.NullString
	err := row.Scan(&api_key)
	return api_key, err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT access_token FROM users
WHERE id = 1
`

func (q *Queries) GetAccessToken(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken)
	var access_token sql.NullString
	err := row.Scan(&access_token)
	return access_token, err
}

const updateAPIKEY = `-- name: UpdateAPIKEY :exec
;

UPDATE users
SET api_key = ?
WHERE id = 1
`

func (q *Queries) UpdateAPIKEY(ctx context.Context, apiKey sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateAPIKEY, apiKey)
	return err
}

const updateToken = `-- name: UpdateToken :exec
;

UPDATE users
SET access_token = ?
WHERE id = 1
`

func (q *Queries) UpdateToken(ctx context.Context, accessToken sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateToken, accessToken)
	return err
}
